name: sim
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_1
  - pip=24.0=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - attrs==23.2.0
      - based-inference==0.0.0
      - causal-attention-cuda-cpp==0.0.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - fla==0.1
      - flash-attn==2.5.0
      - idna==3.7
      - install==1.3.5
      - jinja2==3.1.4
      - lin-attn==0.0.0
      - lin-attn-h100==0.0.0
      - ninja==1.11.1.1
      - packaging==24.0
      - pillow==10.3.0
      - psutil==5.9.8
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.31.0
      - six==1.16.0
      - tc-attend==0.0.0
      - triton==2.2.0
      - typing-extensions==4.11.0
prefix: /home/bfs/miniconda3/envs/sim
