name: nano_gpt
channels:
  - nvidia/label/cuda-11.8.0
  - pytorch # or pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - transformers
    - datasets
    - tiktoken
    - mlflow
    - tqdm
    - azure-ai-ml
    - pyhocon
  - pytorch
  - torchvision
  - torchaudio
  - cuda
  - pytorch-cuda=11.8