name: nanoGPT
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - datasets==2.18.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - huggingface-hub==0.21.4
      - idna==3.6
      - jinja2==3.1.3
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - packaging==23.2
      - pandas==2.0.3
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyarrow==15.0.1
      - pyarrow-hotfix==0.6
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - safetensors==0.4.2
      - sentry-sdk==1.41.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.12
      - tiktoken==0.6.0
      - tokenizers==0.15.2
      - torch==2.2.1
      - tqdm==4.66.2
      - transformers==4.38.2
      - triton==2.2.0
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - wandb==0.16.4
      - xxhash==3.4.1
      - yarl==1.9.4
prefix: /home/jond/miniconda3/envs/nanoGPT
